### ISSUE TITLE
Page issues 

### ISSUE THREAD

**Issue by RPGTheGreat** [Nouridio/Discord-bot-website-template#13]
It's only have index.html not other pages so how it's works and it's show page not found

**Comment by fbagjug** [comment]
It's only a design so you have to write the pages yourself and write the PHP logic yourself :/

**Comment by shahprog** [comment]
check https://customcommands.xyz for demo

**Comment by fbagjug** [comment]
Ahh I see, you beat me to the PHP logic lmao I was busy with IRL stuff :/

**Comment by shahprog** [comment]
I used Flask (Python) though. Not PHP

**Comment by fbagjug** [comment]
Fair enough

**Comment by hiro-akiba** [comment]
@RPGTheGreat the page in this repository is only index.html, if you want more you'll have to learn html and create your own qvq

Also this has to be closed $v$
