### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by Nats-uuu** [Nouridio/Discord-bot-website-template#15]
How to get statistics from the bot on the website

**Comment by SwampDolphin97** [comment]
Statistics of ?

**Comment by NatsIsHereeeeee** [comment]
> Statistics of ?
Statistics of guilds joined, members and channels

**Comment by sadordev** [comment]
> > Statistics of ?
> 
> Statistics of guilds joined, members and channels

this require EJS

**Comment by Ryzesx** [comment]
how do i get that

**Comment by sadordev** [comment]
> how do i get that

https://www.youtube.com/watch?v=DmIkbgJZJ_o&t=544s
