### ISSUE TITLE
Website Svg Broke

### ISSUE THREAD

**Issue by MaxIsDumbLoL** [Nouridio/Discord-bot-website-template#19]
I wanted to change the color to a diff one, the thing is that only one part of the svg is still purple and there's no part tk change the color.

**Comment by Nouridio** [comment]
Open the Svg file and try to change the color code

**Comment by MaxIsDumbLoL** [comment]
> Open the Svg file and try to change the color code

Can i contact you on discord? If yes send me a friend request at: MaxIsDumbLoL#0001
