### ISSUE TITLE
I am getting issues pls help me how to get the website link

### ISSUE THREAD

**Issue by demonisgood133** [Nouridio/Discord-bot-website-template#20]
![Screenshot_2021-03-30-21-32-10-665_com android chrome](https://user-images.githubusercontent.com/80505912/113019604-6bd6d100-919f-11eb-976f-bd8b17d6e563.jpg)

**Comment by UPDOWNUP-64BIT** [comment]
you have to set it up with oauth2 from your bot and connect it to your project
