### ISSUE TITLE
Template copy

### ISSUE THREAD

**Issue by andrelucaas** [Nouridio/Discord-bot-website-template#22]
I found a guy who copied your template, translated it and is pretending to be the author of it: https://github.com/HaloKodein/DiscordBotWebsite

**Comment by thewhistledev** [comment]
**The MIT License states that anyone can use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of this software, meaning the user is completely allowed to remove copyrights and insert their own, as long as the MIT License is stated within the frontend of the software. The user you are reporting is completely allowed to do that**

**Comment by thewhistledev** [comment]
> I found a guy who copied your template, translated it and is pretending to be the author of it: https://github.com/HaloKodein/DiscordBotWebsite

**The MIT License states that anyone can use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of this software, meaning the user is completely allowed to remove copyrights and insert their own, as long as the MIT License is stated within the frontend of the software. The user you are reporting is completely allowed to do that**
