### ISSUE TITLE
Template Copy

### ISSUE THREAD

**Issue by PizzaCuCapsuni** [Nouridio/Discord-bot-website-template#26]
Hello, I found a user who copied your template and remove the credits

link: https://hyper.pratikdev.xyz
![Screenshot_20211212-100815](https://user-images.githubusercontent.com/91821584/145705259-e32fc6a2-c46d-4ffa-aac5-662d84fce0fb.png)
discord: ARCEUS OP#9795
discord user id: 769388701909516288

**Comment by thewhistledev** [comment]
**The MIT License states that anyone can use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of this software, meaning the user is completely allowed to remove copyrights and insert their own, as long as the MIT License is stated within the frontend of the software. The user you are reporting is completely allowed to do that**

**Comment by thewhistledev** [comment]
> Hello, I found a user who copied your template and remove the credits
> 
> link: https://hyper.pratikdev.xyz ![Screenshot_20211212-100815](https://user-images.githubusercontent.com/91821584/145705259-e32fc6a2-c46d-4ffa-aac5-662d84fce0fb.png) discord: ARCEUS OP#9795 discord user id: 769388701909516288

**The MIT License states that anyone can use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of this software, meaning the user is completely allowed to remove copyrights and insert their own, as long as the MIT License is stated within the frontend of the software. The user you are reporting is completely allowed to do that**

**Comment by Nouridio** [comment]
Thanks, I will handle this
