### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by patelom693** [Nouridio/Discord-bot-website-template#27]
What  is  run command?

**Comment by MigPlayer6032** [comment]
Olá, @patelom693! So this repository doesn't need to be run: just open the file [index.html](https://github.com/Nouridio/Discord-bot-website-template/blob/master/src/index.html) in a browser.

**Comment by patelom693** [comment]
Thank you very much for your kindly support 🤗

**Comment by SwampDolphin97** [comment]
@Nouridio
